version: '3.1'
services:


  mysql:
    image: mysql/mysql-server:8.0
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine  
      MYSQL_PASSWORD: secret

  my-redmine:
    build: .
    ports:
      - 80:80
    depends_on:
      - mysql
    restart: always
    command: ["bash", "-c", "RAILS_ENV=production bundle exec rake db:migrate"]



 
